{{ config(materialized='table', schema='SPECIALITYSCHEMA') }}

WITH Doctor_CTE AS (
    SELECT
        ID AS DOCTOR_ID,
        _ID AS CLINIC_ID,
        FULL_NAME_SPECIALTY AS FULL_NAME_OF_SPECIALITY
    FROM "CIS4400HEALTH"."SPECIALITYSCHEMA"."ROW_LOCATION"
)
SELECT *
FROM Doctor_CTE